In [35]:
import numpy as np


In [36]:
CURVE_CENTER=80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):
  avg = grades.mean();
  print(avg)
  change = CURVE_CENTER - avg
  new_grades = grades + change
  return np.clip(new_grades, grades, 100)

curve(grades)

60.75


array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [37]:
temperatures = np.array([29.3, 42.1, 18.8, 16.1, 38.0, 12.5, 12.6, 49.9, 38.6, 31.3, 9.2, 22.2]).reshape(2, 2, 3)# 2 rows, 2 columns and 3 elements each per item in matrix
temperatures.shape
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [38]:
np.swapaxes(temperatures, 1, 2) # Transpose of the matrix

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

In [39]:
 table = np.array([ [5, 3, 7, 1],
                    [2, 6, 7 ,9],
                    [1, 1, 1, 1],
                    [4, 3, 2, 0],])
 print(table.max())
 print(table.max(axis=0))
 print(table.max(axis=1))

9
[5 6 7 9]
[7 9 1 4]


In [40]:
A = np.arange(32).reshape(4, 1, 8)
print("A ={}".format(A))
B = np.arange(48).reshape(1, 6, 8)
print("B = {}".format(B))
print("A+B {}".format(A+B))

A =[[[ 0  1  2  3  4  5  6  7]]

 [[ 8  9 10 11 12 13 14 15]]

 [[16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31]]]
B = [[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]]]
A+B [[[ 0  2  4  6  8 10 12 14]
  [ 8 10 12 14 16 18 20 22]
  [16 18 20 22 24 26 28 30]
  [24 26 28 30 32 34 36 38]
  [32 34 36 38 40 42 44 46]
  [40 42 44 46 48 50 52 54]]

 [[ 8 10 12 14 16 18 20 22]
  [16 18 20 22 24 26 28 30]
  [24 26 28 30 32 34 36 38]
  [32 34 36 38 40 42 44 46]
  [40 42 44 46 48 50 52 54]
  [48 50 52 54 56 58 60 62]]

 [[16 18 20 22 24 26 28 30]
  [24 26 28 30 32 34 36 38]
  [32 34 36 38 40 42 44 46]
  [40 42 44 46 48 50 52 54]
  [48 50 52 54 56 58 60 62]
  [56 58 60 62 64 66 68 70]]

 [[24 26 28 30 32 34 36 38]
  [32 34 36 38 40 42 44 46]
  [40 42 44 46 48 50 52 54]
  [48 50 52 54 56 58 60 62]
  [56 58 60 62 64 66 68 70]
  [64 66 68 70 72 74 76 78]]]


In [41]:
np.arange(32).reshape(4,1,8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [42]:
A = np.arange(8).reshape(1, 4, 2)
print("A ={}".format(A))
print(A[0,1])
B = np.arange(8).reshape(4, 1, 2)
print("B = {}".format(B))
C = A+B
print("A+B {}".format(C))
print(C.shape)

A =[[[0 1]
  [2 3]
  [4 5]
  [6 7]]]
[2 3]
B = [[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]]
A+B [[[ 0  2]
  [ 2  4]
  [ 4  6]
  [ 6  8]]

 [[ 2  4]
  [ 4  6]
  [ 6  8]
  [ 8 10]]

 [[ 4  6]
  [ 6  8]
  [ 8 10]
  [10 12]]

 [[ 6  8]
  [ 8 10]
  [10 12]
  [12 14]]]
(4, 4, 2)


In [43]:
import numpy as np
square=np.arange(100).reshape(5,2,10)
print(square)
print(square[1,1])

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]
[30 31 32 33 34 35 36 37 38 39]


In [44]:
 sq = np.arange(100).reshape(10,10)
 print(sq)
 print(sq[3,5])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
35


In [45]:
a1 = np.arange(1,13)
print(a1)
a2 = a1.reshape(3,4)
print(a2)
a3 = a2.reshape(-1,4)
print(a3)
a4 = a3.reshape(3,-1)
print(a4)
print(type(a4))

a5 = a1.reshape(3,-1, order='F')
print(a5)
#a1.reshape(3,-1).revel()
#print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [46]:
arr = np.arange(100).reshape(-1,10)
print(arr)
print(arr[0,2])
print(arr[0:2])
print(arr[0:2,1])
print(arr.transpose())

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
2
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[ 1 11]
[[ 0 10 20 30 40 50 60 70 80 90]
 [ 1 11 21 31 41 51 61 71 81 91]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 3 13 23 33 43 53 63 73 83 93]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 7 17 27 37 47 57 67 77 87 97]
 [ 8 18 28 38 48 58 68 78 88 98]
 [ 9 19 29 39 49 59 69 79 89 99]]


In [47]:
arr = np.arange(100).reshape(-1,10)
print(arr)
print(arr[3:5,0:10])

arr.flatten()

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
np.where([[True,False],[True,False]], [[1,2],[4,6]], [[11,12],[14,16]])

array([[ 1, 12],
       [ 4, 16]])

In [49]:
arr[3:7,4:8]

array([[34, 35, 36, 37],
       [44, 45, 46, 47],
       [54, 55, 56, 57],
       [64, 65, 66, 67]])

In [50]:
arr1= np.arange(10).reshape(-1,2)
print(arr1)
arr2= np.where(arr1>4)
print(arr2)
arr3= np.where(arr1%4==0)
print(arr3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(array([2, 3, 3, 4, 4]), array([1, 0, 1, 0, 1]))
(array([0, 2, 4]), array([0, 0, 0]))


In [51]:
print(arr2)
arr4 = np.where((arr1>4) & (arr1<8))
print(arr4) 
arr5 = np.where(np.logical_and(arr1<4,arr1>8))
print(arr5) 

(array([2, 3, 3, 4, 4]), array([1, 0, 1, 0, 1]))
(array([2, 3, 3]), array([1, 0, 1]))
(array([], dtype=int64), array([], dtype=int64))


In [52]:
print(arr1.mean())
np.where(arr1>arr1.mean())

4.5


(array([2, 3, 3, 4, 4]), array([1, 0, 1, 0, 1]))