In [37]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [38]:
seriesfromlist1= pd.Series(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],index=[[1,2,3,4,5,6,7]])
print(seriesfromlist1)
seriesfromlist2= pd.Series(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],index=[["M","T","W","T","F","S","S"]])
print(seriesfromlist2)
seriesfromlist3= pd.Series(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],index=list('MTWTFSS'))
print(seriesfromlist3)

1       Monday
2      Tuesday
3    Wednesday
4     Thursday
5       Friday
6     Saturday
7       Sunday
dtype: object
M       Monday
T      Tuesday
W    Wednesday
T     Thursday
F       Friday
S     Saturday
S       Sunday
dtype: object
M       Monday
T      Tuesday
W    Wednesday
T     Thursday
F       Friday
S     Saturday
S       Sunday
dtype: object


In [39]:
days = {1:"Monday", 2:"Tuesday", 3:"Wednesday", 4:"Thursday", 5:"Friday", 6:"Satuday", 7:"Sunday"}
seriesfromdictionary = pd.Series(days)
print(seriesfromdictionary)
seriesfromdictionary1 = pd.Series(days, index=[1,2,3,4,5])
seriesfromdictionary2 = pd.Series(days, index=[1,2,3,4,5,1])
print(seriesfromdictionary1)
print(seriesfromdictionary2)

1       Monday
2      Tuesday
3    Wednesday
4     Thursday
5       Friday
6      Satuday
7       Sunday
dtype: object
1       Monday
2      Tuesday
3    Wednesday
4     Thursday
5       Friday
dtype: object
1       Monday
2      Tuesday
3    Wednesday
4     Thursday
5       Friday
1       Monday
dtype: object


In [40]:
seriesfromdictionary[1] #on index 1
seriesfromdictionary[1:5] #from index 1 to 5
seriesfromdictionary[-2:] #last two elements
seriesfromlist1[1]

1    Monday
dtype: object

In [41]:
print(seriesfromlist1.values)
print(seriesfromlist2.value_counts)
print(seriesfromdictionary.size)
print(seriesfromdictionary.items)
print(seriesfromdictionary.index)
print(seriesfromdictionary1.index)
print(seriesfromdictionary.is_unique)
print(seriesfromdictionary2.is_unique)
print(seriesfromdictionary2.nunique())

print(seriesfromdictionary1.dtype)
print(seriesfromdictionary1.shape)
print(seriesfromdictionary1.ndim)

['Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday' 'Saturday' 'Sunday']
<bound method IndexOpsMixin.value_counts of M       Monday
T      Tuesday
W    Wednesday
T     Thursday
F       Friday
S     Saturday
S       Sunday
dtype: object>
7
<bound method Series.items of 1       Monday
2      Tuesday
3    Wednesday
4     Thursday
5       Friday
6      Satuday
7       Sunday
dtype: object>
Int64Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 2, 3, 4, 5], dtype='int64')
True
False
5
object
(5,)
1


In [42]:
print(seriesfromdictionary)
print(seriesfromdictionary.head())
print(seriesfromdictionary.head(2))
print(seriesfromdictionary.tail(2))

1       Monday
2      Tuesday
3    Wednesday
4     Thursday
5       Friday
6      Satuday
7       Sunday
dtype: object
1       Monday
2      Tuesday
3    Wednesday
4     Thursday
5       Friday
dtype: object
1     Monday
2    Tuesday
dtype: object
6    Satuday
7     Sunday
dtype: object


In [43]:
prices = [10, 5, 3, 2.5, 8, 11]
s = pd.Series(prices)
print(s.mean())

prices.sort()
print(prices)
print(s.median())

print(s.product())

print(s.sort_values(ascending=False))
print(s)
s.sort_values(inplace=True)
print(s)


6.583333333333333
[2.5, 3, 5, 8, 10, 11]
6.5
33000.0
5    11.0
0    10.0
4     8.0
1     5.0
2     3.0
3     2.5
dtype: float64
0    10.0
1     5.0
2     3.0
3     2.5
4     8.0
5    11.0
dtype: float64
3     2.5
2     3.0
1     5.0
4     8.0
0    10.0
5    11.0
dtype: float64


In [44]:
print(s.le(6))
print(list(s))
print(dict(s))

3     True
2     True
1     True
4    False
0    False
5    False
dtype: bool
[2.5, 3.0, 5.0, 8.0, 10.0, 11.0]
{3: 2.5, 2: 3.0, 1: 5.0, 4: 8.0, 0: 10.0, 5: 11.0}


In [45]:
data = [1,2,3]
#df from a list
dfl = pd.DataFrame(data, columns=["Number"])
dfl

#df from n dimension list
ndlist = [[1,"Shashwat"],[2,"Vished"],[3,"Arjun"]]
dfndl= pd.DataFrame(ndlist, columns=["Roll Number","Name"])
dfndl

df1 = DataFrame(np.arange(1,26).reshape(-1,5),index=list("ABCDE"), columns=list("VWXYZ"))
df1

df2 = DataFrame({"Company":list("ABCDE"), "Price":list(np.random.randint(1,101,5))})
df2

Company  Price
0       A     54
1       B     39
2       C     69
3       D     25
4       E      8

In [46]:
print(dfndl['Name'])
print(dfndl['Name'][1])


0    Shashwat
1      Vished
2       Arjun
Name: Name, dtype: object
Vished


In [47]:
df = DataFrame(np.arange(1,26).reshape(-1,5))
df

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [48]:
print(df.columns)
print(df.values)

RangeIndex(start=0, stop=5, step=1)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [49]:
print(df1[['V','X']]) # reference from rows
print(df1[1:4]) #reference from columns, index non-inclusive

    V   X
A   1   3
B   6   8
C  11  13
D  16  18
E  21  23
    V   W   X   Y   Z
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20


In [50]:
print(df1['V'])
print(df1[df1['V'] < 12])

A     1
B     6
C    11
D    16
E    21
Name: V, dtype: int64
    V   W   X   Y   Z
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15


In [51]:
df2 = DataFrame({"Company":list("ABCDE"), "Price":list(np.random.randint(1,101,5))})
df2

df2['DP'] = df2["Price"]*.90
df2

df2["City"] = "Mumbai"
df2

df2 = df2[df2["City"]=="Mumbai"]
df2

Company  Price    DP    City
0       A     64  57.6  Mumbai
1       B     11   9.9  Mumbai
2       C     34  30.6  Mumbai
3       D     72  64.8  Mumbai
4       E     24  21.6  Mumbai

In [52]:
df2["City"] =list("MSFDM")
df2

df2[df2["City"] == 'M']

df2[(df2["City"] == 'M') & (df2["Price"] > 1)]

Company  Price    DP City
0       A     64  57.6    M
4       E     24  21.6    M

In [53]:
#delete column
del df2["DP"] 
df2

Company  Price City
0       A     64    M
1       B     11    S
2       C     34    F
3       D     72    D
4       E     24    M

In [54]:
df2.drop("City", axis=1)
df2.drop(1, axis=0)

df2.drop(4, axis=0, inplace=True)
df2

Company  Price City
0       A     64    M
1       B     11    S
2       C     34    F
3       D     72    D

In [55]:
df2.iloc[0,0]

'A'

In [56]:
df2.iloc[0:3]

Company  Price City
0       A     64    M
1       B     11    S
2       C     34    F

In [57]:
df2.iloc[::2]

Company  Price City
0       A     64    M
2       C     34    F

In [58]:
df3 = df2.copy()

In [59]:
df3.iloc[0,1]

64

In [60]:
df3.iloc[0:3]

Company  Price City
0       A     64    M
1       B     11    S
2       C     34    F

In [61]:
df2.loc[:,'City']

0    M
1    S
2    F
3    D
Name: City, dtype: object

In [62]:
df2.loc[3,'Price']

72

In [63]:
df3[0:3]

Company  Price City
0       A     64    M
1       B     11    S
2       C     34    F

In [64]:
print(df2)
df2.iloc[3,1]

  Company  Price City
0       A     64    M
1       B     11    S
2       C     34    F
3       D     72    D


72

In [65]:
df3.iloc[1:3, 1] = 75
df3

Company  Price City
0       A     64    M
1       B     75    S
2       C     75    F
3       D     72    D

In [66]:
df3.iloc[1:3, 0] = 'Z'
df3

Company  Price City
0       A     64    M
1       Z     75    S
2       Z     75    F
3       D     72    D

In [67]:
df2.rename({"City":"Town"},axis=1, inplace=True)
df2

Company  Price Town
0       A     64    M
1       B     11    S
2       C     34    F
3       D     72    D

In [68]:
df2.rename({0:"A"}, axis=0, inplace=True)
df2

Company  Price Town
A       A     64    M
1       B     11    S
2       C     34    F
3       D     72    D

In [69]:
df2.replace(['M','D'],["Mumbai","Delhi"], inplace=True)
df2

Company  Price    Town
A       A     64  Mumbai
1       B     11       S
2       C     34       F
3   Delhi     72   Delhi

In [70]:
df3 = DataFrame({'Name':list('ABCDEFGHIJ'), 'Score 1': np.random.randint(1,101,10)})
df3

Name  Score 1
0    A       68
1    B       84
2    C       20
3    D       68
4    E       76
5    F       10
6    G       56
7    H       41
8    I       80
9    J       56

In [71]:
df3.sort_values(by='Score 1', ascending=False)

Name  Score 1
1    B       84
8    I       80
4    E       76
0    A       68
3    D       68
6    G       56
9    J       56
7    H       41
2    C       20
5    F       10

In [72]:
df3.sort_values(by='Score 1', ascending=False, inplace=True)

In [73]:
df3.sort_values(by="Score 1",ascending=False, inplace=True)
df3

Name  Score 1
1    B       84
8    I       80
4    E       76
0    A       68
3    D       68
6    G       56
9    J       56
7    H       41
2    C       20
5    F       10

In [74]:
df3.sort_index(inplace=True)
df3

Name  Score 1
0    A       68
1    B       84
2    C       20
3    D       68
4    E       76
5    F       10
6    G       56
7    H       41
8    I       80
9    J       56

In [75]:
df3["Rank"] = df3["Score 1"].rank()
df3

Name  Score 1  Rank
0    A       68   6.5
1    B       84  10.0
2    C       20   2.0
3    D       68   6.5
4    E       76   8.0
5    F       10   1.0
6    G       56   4.5
7    H       41   3.0
8    I       80   9.0
9    J       56   4.5

In [76]:
df3["Rank Min"] = df3["Score 1"].rank(method='min')
df3

Name  Score 1  Rank  Rank Min
0    A       68   6.5       6.0
1    B       84  10.0      10.0
2    C       20   2.0       2.0
3    D       68   6.5       6.0
4    E       76   8.0       8.0
5    F       10   1.0       1.0
6    G       56   4.5       4.0
7    H       41   3.0       3.0
8    I       80   9.0       9.0
9    J       56   4.5       4.0

In [77]:

df3['Rank Dense'] = df3['Score 1'].rank(method='dense')
df3

Name  Score 1  Rank  Rank Min  Rank Dense
0    A       68   6.5       6.0         5.0
1    B       84  10.0      10.0         8.0
2    C       20   2.0       2.0         2.0
3    D       68   6.5       6.0         5.0
4    E       76   8.0       8.0         6.0
5    F       10   1.0       1.0         1.0
6    G       56   4.5       4.0         4.0
7    H       41   3.0       3.0         3.0
8    I       80   9.0       9.0         7.0
9    J       56   4.5       4.0         4.0

In [78]:
df4 = DataFrame({'A': [1, np.nan, np.nan, np.nan],
                 'B': [2,4,7, np.nan],
                'C':[3,5,np.nan,np.nan]})
df4

A    B    C
0  1.0  2.0  3.0
1  NaN  4.0  5.0
2  NaN  7.0  NaN
3  NaN  NaN  NaN

In [79]:
df4 = DataFrame([[1,2,3],[np.nan,4,5], [np.nan,7,np.nan],[np.nan,np.nan,np.nan]], columns=list('ABC'))
df4

A    B    C
0  1.0  2.0  3.0
1  NaN  4.0  5.0
2  NaN  7.0  NaN
3  NaN  NaN  NaN

In [80]:
df4['A'].isnull()

0    False
1     True
2     True
3     True
Name: A, dtype: bool

In [81]:
df4['A'].notnull()

0     True
1    False
2    False
3    False
Name: A, dtype: bool

In [82]:
df4['A'].notnull().sum()

1

In [83]:
df4.dropna()

A    B    C
0  1.0  2.0  3.0

In [84]:
df4.dropna(how="all")

A    B    C
0  1.0  2.0  3.0
1  NaN  4.0  5.0
2  NaN  7.0  NaN

In [85]:
df4.dropna(thresh=2)

A    B    C
0  1.0  2.0  3.0
1  NaN  4.0  5.0

In [86]:
df4.T

0    1    2   3
A  1.0  NaN  NaN NaN
B  2.0  4.0  7.0 NaN
C  3.0  5.0  NaN NaN

In [87]:
df4.fillna(0, inplace=True)
df4

A    B    C
0  1.0  2.0  3.0
1  0.0  4.0  5.0
2  0.0  7.0  0.0
3  0.0  0.0  0.0

In [88]:
print(df4.mean())
print(df4['C'].mean())

A    0.25
B    3.25
C    2.00
dtype: float64
2.0


In [89]:
df5 = DataFrame({'Key 1': list('AAABB'), 'Key 2': [2,2,3,3,3]})
df5

Key 1  Key 2
0     A      2
1     A      2
2     A      3
3     B      3
4     B      3

In [90]:
df5.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [91]:
df5.duplicated(keep='last')

0     True
1    False
2    False
3     True
4    False
dtype: bool

In [92]:
df5["Key 1"].duplicated()

0    False
1     True
2     True
3    False
4     True
Name: Key 1, dtype: bool

In [93]:
df5.drop_duplicates()

Key 1  Key 2
0     A      2
2     A      3
3     B      3

In [94]:
df7 = DataFrame({'Variable': list('AAABBBCCCDDD'),
                 'Value': [1,2,3]*4,
                 'Data': np.random.randn(12)})
df7

Variable  Value      Data
0         A      1  0.601022
1         A      2  0.632726
2         A      3  0.268386
3         B      1 -0.581174
4         B      2  0.607474
5         B      3 -1.008110
6         C      1 -1.484106
7         C      2  0.038219
8         C      3  0.465464
9         D      1  2.153584
10        D      2 -0.991161
11        D      3  0.655702

In [95]:
df7.pivot('Variable', 'Value', 'Data')

Value            1         2         3
Variable                              
A         0.601022  0.632726  0.268386
B        -0.581174  0.607474 -1.008110
C        -1.484106  0.038219  0.465464
D         2.153584 -0.991161  0.655702

In [96]:
df7.shape

(12, 3)

In [97]:
import urllib.request as request

weburl = request.urlopen("http://www.google.com")
print("Result code: " + str(weburl.getcode()))

data = weburl.read()
print(type(data))
print(data)

Result code: 200
<class 'bytes'>
b'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world\'s information, including webpages, images, videos and more. Google has many special features to help you find exactly what you\'re looking for." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/logos/doodles/2021/seasonal-holidays-2021-6753651837109324-law.gif" itemprop="image"><meta content="Seasonal Holidays 2021" property="twitter:title"><meta content="Seasonal Holidays 2021 #GoogleDoodle" property="twitter:description"><meta content="Seasonal Holidays 2021 #GoogleDoodle" property="og:description"><meta content="summary_large_image" property="twitter:card"><meta content="@GoogleDoodles" property="twitter:site"><meta content="https://www.google.com/logos/doodles/2021/seasonal-holidays-2021-6753651837109324-2xa.gif" property="twitter:image"><met

In [98]:
import json 
weburl = request.urlopen("http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson")
print("Result code: " + str(weburl.getcode()))

data = weburl.read()
print(data)

thejson = json.loads(data)
print(thejson)

if "title" in thejson["metadata"]:
  print(thejson["metadata"]["title"])


count = thejson["metadata"]["count"]
print(count)

print("----------------------------------------")
for i in thejson["features"]:
  print(i["properties"]["place"])


print("----------------------------------------")

for i in thejson["features"]:
  if i["properties"]["mag"] > 2.5:
    print(i["properties"]["place"])

Result code: 200
b'{"type":"FeatureCollection","metadata":{"generated":1638107695000,"url":"https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson","title":"USGS Magnitude 2.5+ Earthquakes, Past Day","status":200,"api":"1.10.3","count":56},"features":[{"type":"Feature","properties":{"mag":2.9,"place":"56 km S of Whites City, New Mexico","time":1638106472986,"updated":1638107388835,"tz":null,"url":"https://earthquake.usgs.gov/earthquakes/eventpage/tx2021xhuk","detail":"https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/tx2021xhuk.geojson","felt":null,"cdi":null,"mmi":null,"alert":null,"status":"reviewed","tsunami":0,"sig":129,"net":"tx","code":"2021xhuk","ids":",us7000fxr3,tx2021xhuk,","sources":",us,tx,","types":",origin,phase-data,","nst":14,"dmin":0.1027023015,"rms":0.3,"gap":60,"magType":"ml","type":"earthquake","title":"M 2.9 - 56 km S of Whites City, New Mexico"},"geometry":{"type":"Point","coordinates":[-104.3803075,31.66774561,7.391259766]},"id":"tx2021x